# Generated by Django 4.1.7 on 2023-02-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\achal\\OneDrive\\Documents\\Monsoon\\ImageUploader\\media'),
        ),
    ]
